var LAST_DAY_CHAPTERS = [
  {
    id: 'before',
    nav: 'Before',
    kicker: 'Before the impact',
    title: 'A world still alive',
    time: 'Late Cretaceous · just before 66 Ma',
    body: '<p>The Late Cretaceous world was not primitive. It was a fully developed biosphere, rich in diversity and tightly networked. Flowering plants had transformed terrestrial ecosystems over the preceding thirty million years, producing forests, meadows, and flowering understories that did not exist when the dinosaurs first arose.</p>' +
          '<p><b>Non-avian dinosaurs</b> were abundant and varied: large ceratopsians like <em>Triceratops</em>, hadrosaurs like <em>Edmontosaurus</em>, ankylosaurs, pachycephalosaurs, and apex predators including <em>Tyrannosaurus rex</em> occupied North American habitats. South America, Asia, Africa, and Europe each had their own faunas. The seas were ruled by <b>mosasaurs</b> and populated by <b>plesiosaurs</b>, ammonites, and fish. <b>Pterosaurs</b> still soared overhead, including the colossal <em>Quetzalcoatlus</em>.</p>' +
          '<p>Mammals were small, mostly nocturnal, and ecologically marginal. Birds - avian dinosaurs - were diversifying. The world was warm, sea levels were high, and shallow epicontinental seas divided continents. Nothing in the fossil record suggests an imminent catastrophe.</p>',
    links: ['tyrannosaurus','triceratops','edmontosaurus','ankylosaurus','pachycephalosaurus','quetzalcoatlus','hatzegopteryx','mosasaurus'],
    facts: null,
    chain: null,
    afterHTML: null,
    img: { src: 'images/the_last_day/before_impact.jpg', alt: 'Late Cretaceous ecosystem before the end-Cretaceous impact', caption: 'A living Late Cretaceous world before the boundary event.', contain: false, position: null }
  },
  {
    id: 'impact',
    nav: 'Impact',
    kicker: 'The Chicxulub impact',
    title: 'Chicxulub',
    time: 'The impact · ~66 Ma',
    body: '<p>Approximately 66 million years ago, a rocky body roughly <b>10–15 kilometres across</b> struck the shallow marine platform of what is now the Yucatán Peninsula of Mexico at an estimated velocity of around 20 kilometres per second. The energy released was approximately one billion times that of the atomic bombs dropped on Hiroshima and Nagasaki combined.</p>' +
          '<p>The target rocks were particularly consequential: thick deposits of <b>limestone and gypsum</b> - carbonates and sulfates - vaporised instantly, injecting enormous quantities of <b>carbon dioxide and sulfur dioxide</b> into the atmosphere alongside pulverised rock and superheated debris. The resulting crater, now known as Chicxulub, is approximately 180 kilometres in diameter and buried beneath the Yucatán and the Gulf of Mexico.</p>' +
          '<p>The impactor itself was likely a <b>carbonaceous chondrite</b> or silicate asteroid. Its extraterrestrial origin is fingerprinted in the global abundance of <b>iridium</b> - rare in the Earth\'s crust but enriched at the K–Pg boundary clay layer found in rocks on every continent.</p>',
    links: null,
    facts: [
      { k: 'Impact site',     v: 'Yucatán Peninsula, Mexico' },
      { k: 'Crater name',     v: 'Chicxulub' },
      { k: 'Crater diameter', v: '~180 km' },
      { k: 'Impactor size',   v: '~10–15 km diameter' },
      { k: 'Age',             v: '66.043 ± 0.011 Ma' },
      { k: 'Target rocks',    v: 'Carbonates & sulfates' }
    ],
    chain: null,
    afterHTML: null,
    img: { src: 'images/the_last_day/chicxulub_impact.jpg', alt: 'Artist impression of the Chicxulub asteroid impact', caption: 'The Chicxulub impact struck carbonate- and sulfate-rich rocks near the Yucatán.', contain: false, position: null }
  },
  {
    id: 'hours',
    nav: 'First Hours',
    kicker: 'Minutes to days',
    title: 'Heat, waves, and falling sky',
    time: 'Minutes to days after impact',
    body: '<p>The immediate aftermath was catastrophic on a regional and then global scale. The impact generated <b>megatsunami</b> that swept across the Gulf of Mexico and beyond. Earthquake-scale seismic waves propagated globally. Superheated ejecta - vaporised and pulverised rock - was thrown into ballistic trajectories and re-entered the atmosphere across the entire planet, briefly heating the upper atmosphere to temperatures that may have ignited wildfires across continents.</p>' +
          '<p>Within hours, the sky was darkened by debris. Within days, a global layer of fine dust and sulfate aerosols began reducing sunlight reaching the surface. The initial thermal pulse may have been survivable in some habitats - underground, underwater, in burrows - but the disruption to the atmosphere had only just begun.</p>' +
          '<p>The sulfur dioxide injected from the vaporised Yucatán gypsum beds converted to <b>sulfate aerosols</b>, which are particularly effective at blocking solar radiation and may have persisted in the stratosphere for years, driving what researchers now call the <b>impact winter</b>.</p>',
    links: null,
    facts: null,
    chain: null,
    afterHTML: null,
    img: { src: 'images/the_last_day/chicxulub_tsunami.jpg', alt: 'Chicxulub impact crater aerial illustration', caption: 'The impact triggered extreme waves, seismic disturbance and debris fallout.', contain: false, position: null }
  },
  {
    id: 'dark',
    nav: 'Long Dark',
    kicker: 'Months to years',
    title: 'When the food chains broke',
    time: 'Months to years after impact',
    body: '<p>The most destructive long-term consequence of the impact was not the blast, the heat, or the tsunamis. It was the interruption of photosynthesis. With sunlight reduced, land plants died back catastrophically. In the oceans, <b>phytoplankton</b> - the base of almost every marine food chain - collapsed. Darkness and cold spread globally.</p>' +
          '<p>This is the <b>food-web collapse cascade</b> that drove the mass extinction. The impact itself likely killed few animals directly outside the immediate blast zone. What killed most species over the following months and years was starvation - the removal of the energy foundation that all food chains rested on.</p>' +
          '<p>Animals with low energy requirements, those able to feed on detritus or seeds that persisted after plants died, and those with short generation times had advantages. Large-bodied animals dependent on continuous food supply - including most non-avian dinosaurs - did not. The <b>impact winter</b> persisted for months to years; full ecosystem recovery took millions of years.</p>',
    links: null,
    facts: null,
    chain: [
      { num: '01', label: 'Impact',            desc: 'Asteroid strikes carbonate- & sulfate-rich rocks on Yucatán at ~20 km/s' },
      { num: '02', label: 'Ejecta & aerosols', desc: 'Dust, soot, and sulfate aerosols reach the upper atmosphere globally within hours to days' },
      { num: '03', label: 'Sunlight blocked',  desc: 'Photosynthesis drops sharply across land and ocean for months to years' },
      { num: '04', label: 'Plants & plankton', desc: 'Primary production at the base of every food chain collapses or crashes' },
      { num: '05', label: 'Herbivores fail',   desc: 'Land and marine herbivores cannot find sufficient food' },
      { num: '06', label: 'Predators follow',  desc: 'Carnivores lose prey; food webs unravel from the top down' },
      { num: '07', label: 'Long recovery',     desc: 'Ecosystems rebuild over thousands to millions of years in the early Cenozoic' }
    ],
    afterHTML: null,
    img: { src: 'images/the_last_day/impact_winter.jpg', alt: 'Darkened post-impact landscape during impact winter', caption: 'Dust, soot and sulfate aerosols reduced sunlight and disrupted photosynthesis.', contain: false, position: 'center 45%' }
  },
  {
    id: 'losses',
    nav: 'Losses',
    kicker: 'The K–Pg extinction',
    title: 'The losses',
    time: 'Across the K–Pg boundary',
    body: '<p>The end-Cretaceous extinction eliminated an estimated <b>75% of all species on Earth</b>. The losses cut across every environment: terrestrial, marine, and freshwater.</p>' +
          '<p>Among the most visible losses: all <b>non-avian dinosaurs</b>, all <b>pterosaurs</b>, all <b>mosasaurs</b>, all <b>plesiosaurs</b>, and all <b>ammonites</b>. In the sea, many species of fish, marine invertebrates, and reef-building organisms perished. On land, many lineages of lizards, snakes, and early mammals were eliminated alongside the dinosaurs.</p>' +
          '<p>The K–Pg boundary - the rock layer marking the end of the Cretaceous Period and the beginning of the Paleogene - is one of the sharpest faunal transitions in the geological record. In many sections, the last fossils of non-avian dinosaurs lie immediately below a layer of clay enriched in iridium, above which no non-avian dinosaur fossils appear.</p>' +
          '<p>The extinction was not instantaneous in every lineage, and some groups may have declined over a short interval following the impact. But the evidence overwhelmingly points to a geologically sudden event rather than a prolonged decline.</p>',
    links: ['tyrannosaurus','triceratops','edmontosaurus','ankylosaurus','pachycephalosaurus','quetzalcoatlus','hatzegopteryx','mosasaurus'],
    facts: null,
    chain: null,
    afterHTML: null,
    img: { src: 'images/the_last_day/the_losses.jpg', alt: 'End-Cretaceous extinction scene showing a disrupted post-impact world', caption: 'The extinction cut across land, sea and sky.', contain: false, position: null }
  },
  {
    id: 'survivors',
    nav: 'Survivors',
    kicker: 'After the boundary',
    title: 'The survivors',
    time: 'The K–Pg boundary and after',
    body: '<p>Survival at the K–Pg boundary was not random, but neither was it predictable from any single trait. The groups that made it through shared certain characteristics: <b>small body size</b>, dietary flexibility, low metabolic requirements, or access to food sources that persisted through the impact winter.</p>' +
          '<p>Some lineages of <b>birds</b> survived - these were avian dinosaurs, the only dinosaur lineage to cross the boundary. Every living bird is a direct descendant of dinosaurs that survived the end-Cretaceous extinction. Some <b>mammals</b> survived, setting the stage for the Cenozoic mammal radiation. <b>Crocodyliforms</b>, turtles, lizards, snakes, frogs, salamanders, and many freshwater invertebrates largely persisted. In the sea, sharks, bony fish, and many invertebrate groups survived.</p>' +
          '<p>The pattern that emerges is one of selective extinction: the larger, more specialised, more food-dependent animals died; the smaller, more flexible, more tolerant ones lived. It was not a question of which animals were \'better\' in any absolute sense - the survivors were simply better suited to the sudden and specific conditions of a world without reliable sunlight.</p>',
    links: null,
    facts: null,
    chain: null,
    afterHTML: '<div class="survival-grid" id="survivalGrid" style="margin-top:28px;"></div>',
    img: { src: 'images/the_last_day/survivors.jpg', alt: 'Animals surviving in the aftermath of the end-Cretaceous extinction', caption: 'Survival favoured smaller, flexible animals able to endure a disrupted world.', contain: false, position: '70% 25%' }
  },
  {
    id: 'after',
    nav: 'Aftermath',
    kicker: 'Early Cenozoic',
    title: 'Dinosaurs after dinosaurs',
    time: 'Early Cenozoic · 66–60 Ma',
    body: '<p>The early Cenozoic - the Paleogene Period - was not simply the world without dinosaurs. It was a world being rebuilt from the ground up. Ecosystems that had been shaped over tens of millions of years had to reassemble from survivors, many of whom had previously been ecologically marginal.</p>' +
          '<p>Mammals, freed from ecological pressure from large non-avian dinosaurs, diversified explosively. Within a few million years of the boundary, the first large mammals appeared. Within ten million years, hoofed herbivores, early whales, bats, and primates were established. The <b>Paleocene–Eocene Thermal Maximum</b> around 56 Ma further transformed ecosystems.</p>' +
          '<p>Birds diversified into roles previously occupied by pterosaurs and small theropod dinosaurs: ground-dwelling predators, aerial insectivores, seed-eaters, and waterbirds. The avian radiation of the early Cenozoic produced most of the major modern bird lineages.</p>' +
          '<p>The world the extinction made possible is the world we live in. Every large mammal, every songbird, every flowering meadow is part of an ecological order that began when the non-avian dinosaurs ended.</p>',
    links: null,
    facts: null,
    chain: null,
    afterHTML: '<div style="margin-top:28px"><button class="ld-people-card" onclick="openPersonModal(\'luis-walter-alvarez\')" aria-label="Open Fossil Hunters profile for Luis &amp; Walter Alvarez"><span class="ld-people-card-kicker">Fossil Hunters Profile</span><span class="ld-people-card-name">Luis &amp; Walter Alvarez</span><span class="ld-people-card-role">Proposed the impact hypothesis · Discovered the iridium anomaly · 1980</span></button></div>',
    img: { src: 'images/the_last_day/dinosaurs_after_dinosaurs.jpg', alt: 'Early Cenozoic ecosystem rebuilding after the end-Cretaceous extinction', caption: 'After the boundary, ecosystems rebuilt around surviving birds, mammals, reptiles and flowering plants.', contain: false, position: null }
  },
  {
    id: 'evidence',
    nav: 'Evidence',
    kicker: 'How we know',
    title: 'The evidence layer',
    time: 'The K–Pg boundary in rock',
    body: '<p>The impact hypothesis for the end-Cretaceous extinction was proposed in 1980 by physicist <b>Luis Alvarez</b>, his geologist son <b>Walter Alvarez</b>, and colleagues Frank Asaro and Helen Michel. They discovered that a thin clay layer at the K–Pg boundary in Gubbio, Italy, contained concentrations of <b>iridium</b> roughly thirty times higher than surrounding rocks. Iridium is rare in Earth\'s crust but common in certain types of asteroids.</p>' +
          '<p>Subsequent research confirmed the iridium anomaly at hundreds of K–Pg boundary sites worldwide. Additional physical evidence accumulated: <b>shocked quartz</b> - quartz grains with microscopic planar deformation features that form only under extreme pressures, consistent with impact or nuclear explosion - was found globally at the boundary. <b>Impact spherules</b>, tiny glassy droplets of vaporised rock that solidified as they fell back through the atmosphere, were identified in boundary clay across the globe.</p>' +
          '<p>The crater itself was identified in the late 1970s and confirmed in the 1990s by geophysical surveys and deep drilling on the Yucatán Peninsula. The Chicxulub crater, now buried beneath a kilometre of younger sediment, matches the age and scale predicted by the impact hypothesis precisely. Scientific consensus on the impact as the primary driver of the K–Pg extinction is strong.</p>',
    links: null,
    facts: [
      { k: 'Iridium anomaly',  v: 'Global enrichment at K–Pg boundary clay' },
      { k: 'Shocked quartz',   v: 'Planar deformation features in quartz grains' },
      { k: 'Impact spherules', v: 'Glassy droplets from vaporised rock' },
      { k: 'Chicxulub crater', v: 'Confirmed by drilling and geophysics' },
      { k: 'Tsunami deposits', v: 'Disturbed sediments in Gulf region sites' },
      { k: 'Fossil turnover',  v: 'Abrupt last occurrence of non-avian dinosaurs' }
    ],
    chain: null,
    afterHTML: null,
    img: { src: 'images/the_last_day/k_pg_boundary.jpg', alt: 'K-Pg boundary clay layer in rock', caption: 'A visible K–Pg boundary layer: the geological line that helped reveal the impact event.', contain: true, position: null }
  }
];

var SURVIVAL_GROUPS = [
  { group: 'Non-avian dinosaurs', fate: 'Extinct', tone: 'loss',
    why: 'All non-avian dinosaurs were eliminated at or shortly after the K–Pg boundary. Large body size, dependence on abundant plant food, and egg-laying with potentially long incubation may all have been disadvantages when food webs collapsed. No non-avian dinosaur lineage is known from any post-boundary deposit.',
    examples: ['tyrannosaurus','triceratops','edmontosaurus','ankylosaurus'] },
  { group: 'Pterosaurs', fate: 'Extinct', tone: 'loss',
    why: 'All pterosaurs were gone by the end of the Cretaceous. Their diversity had already reduced in the latest Cretaceous. Aerial lifestyles dependent on flying prey and fish may have been particularly vulnerable once food webs crashed.',
    examples: ['quetzalcoatlus'] },
  { group: 'Mosasaurs & plesiosaurs', fate: 'Extinct', tone: 'loss',
    why: 'Both groups depended heavily on marine food webs severely disrupted when photosynthesis collapsed and plankton declined. Neither mosasaurs nor plesiosaurs were dinosaurs - they were distinct lineages of marine reptiles.',
    examples: ['mosasaurus'] },
  { group: 'Ammonites', fate: 'Extinct', tone: 'loss',
    why: 'Ammonites - abundant for hundreds of millions of years - were entirely eliminated at the boundary. Their extinction is one of the clearest marine signals of the K–Pg event.',
    examples: [] },
  { group: 'Avian dinosaurs (birds)', fate: 'Some survived', tone: 'some',
    why: 'Some lineages of birds survived the boundary, giving rise to all living species. Many Late Cretaceous bird lineages also perished. Survivors may have benefited from small body size, flexible diets including seeds and insects, and rapid reproduction. Every living bird is a surviving dinosaur.',
    examples: [] },
  { group: 'Mammals', fate: 'Some survived', tone: 'some',
    why: 'Many mammal species died at the boundary. Survivors tended to be small-bodied with flexible diets including seeds, insects, carrion, and detritus. Short generation times allowed faster recovery. The entire Cenozoic mammal radiation was built on K–Pg survivors.',
    examples: [] },
  { group: 'Crocodyliforms', fate: 'Some survived', tone: 'some',
    why: 'Crocodyliforms survived into the Cenozoic. Semi-aquatic habits, low metabolic rates, the ability to fast for extended periods, and freshwater food chains may all have helped them outlast their contemporaries.',
    examples: [] },
  { group: 'Freshwater animals', fate: 'Many survived', tone: 'survived',
    why: 'Turtles, freshwater fish, frogs, salamanders, and many freshwater invertebrates largely survived. Freshwater ecosystems that depend on detritus-based food chains may have been partly buffered from the collapse in land-plant photosynthesis.',
    examples: [] }
];

var FOSSILS_SCIENCE_CASES = [
  {
    id: 'anning-marine-reptiles',
    number: '01',
    title: 'Mary Anning and the Sea Dragons',
    subtitle: 'Lyme Regis, England - 1811–1830s',
    image: 'images/fossils/anning_marine_reptile.jpg',
    alt: 'Marine reptile fossil linked to Mary Anning\'s discoveries',
    caption: 'Marine reptile fossil representing the discoveries that helped reveal extinct Jurassic seas.',
    contain: false,
    before: 'Before the 1810s, the idea that entire species could vanish from the Earth was deeply uncomfortable for most naturalists. Extinction contradicted prevailing beliefs about divine creation. Ocean-going reptiles larger than any living creature were beyond imagination.',
    showed: 'Anning\'s excavations from the Blue Lias cliffs at Lyme Regis produced the first scientifically recognised ichthyosaur skeleton (1811–12) and the first complete plesiosaur (1823). These were not fish, not mammals, not any living group - they were extinct reptiles adapted for marine life, proving beyond doubt that extinction was a real phenomenon.',
    how: 'The specimens were unlike anything alive. Ichthyosaurs had fish-like tails but reptilian skulls and gave birth to live young (evidenced by juveniles found inside adults). Plesiosaurs had extraordinarily long necks and four flippers. Both demanded a new category of creature and forced naturalists to accept deep time and wholesale species loss.',
    nuance: 'Anning was a working-class woman with no formal scientific training. She identified, excavated, prepared and sold the specimens; the gentlemen naturalists who described and named them took the credit. Her contribution was not fully acknowledged by the scientific establishment in her lifetime.',
    species: ['ichthyosaurus', 'plesiosaurus', 'elasmosaurus'],
    people: ['mary-anning'],
    researchCases: [],
    lastDay: false
  },
  {
    id: 'iguanodon-teeth-thumb',
    number: '02',
    title: 'Teeth Like an Iguana - But Enormous',
    subtitle: 'Sussex, England - 1822',
    image: 'images/fossils/iguanodon_teeth_and_thumb_spike.jpg',
    alt: 'Iguanodon teeth and thumb spike fossils',
    caption: 'Iguanodon teeth and thumb spike material show how early dinosaur reconstructions changed.',
    contain: false,
    before: 'In the early 1820s, large fossil bones were known but invariably attributed to giant humans, elephants, or sea monsters. No framework existed for giant terrestrial reptiles.',
    showed: 'Gideon Mantell\'s discovery of large fossilised teeth in Sussex - later confirmed as Iguanodon - and his comparison of them to iguana teeth at a smaller scale led him to propose a giant, plant-eating, iguana-like reptile had once walked England. When Richard Owen later examined Iguanodon alongside Megalosaurus and Hylaeosaurus, he coined the term "Dinosauria" (1842), creating an entirely new group of animals.',
    how: 'Mantell recognised that the teeth were not from any known marine animal; their chisel-like wear pattern matched herbivory. The scale implied an animal far larger than any living reptile. Owen\'s synthesis of multiple finds into "Dinosauria" - terrible lizards - established that a distinct, ancient, and now extinct group of reptiles had dominated the land.',
    nuance: 'The initial reconstruction placed the spiked thumb bone on Iguanodon\'s nose, like a rhinoceros horn. The thumb-spike correction came decades later when articulated specimens were found in Belgium (1878). Owen and Mantell had a bitter, career-long rivalry that often influenced how credit was assigned.',
    species: ['iguanodon'],
    people: ['gideon-mantell', 'richard-owen'],
    researchCases: [],
    lastDay: false
  },
  {
    id: 'archaeopteryx-fossil',
    number: '03',
    title: 'The Urvogel - First Bird or Feathered Reptile?',
    subtitle: 'Solnhofen, Bavaria - 1861',
    image: 'images/fossils/berlin_archaeopteryx.jpg',
    alt: 'Berlin Archaeopteryx fossil specimen',
    caption: 'The Berlin Archaeopteryx specimen, one of the most famous transitional fossils.',
    contain: true,
    before: 'Darwin\'s On the Origin of Species had just been published (1859). Critics demanded transitional fossils. The gap between reptiles and birds seemed unbridgeable. Feathers were considered a uniquely avian structure.',
    showed: 'The Solnhofen limestone quarries yielded Archaeopteryx lithographica - a creature with unmistakably bird-like feathers preserved in fine detail, but also a long bony tail, clawed hands, and teeth: features no living bird possesses. It was, undeniably, an intermediate form.',
    how: 'Archaeopteryx had asymmetric flight feathers (indicating aerodynamic function), a wishbone (furcula), and a brain shape suggesting visual processing for flight. But its skeleton was almost indistinguishable from small theropod dinosaurs - it lacked a fused tail (pygostyle), had three separate clawed fingers, and retained teeth. It demonstrated that birds evolved from within the reptile lineage.',
    nuance: 'Archaeopteryx was later shown not to be the direct ancestor of modern birds but rather an early branch of the avian lineage - or possibly even outside it, depending on the analysis. The discovery that many non-avian dinosaurs also had feathers (see Case 09) complicated the picture further.',
    species: ['archaeopteryx'],
    people: [],
    researchCases: ['feathers', 'family-tree', 'dinosaur-colours'],
    lastDay: false
  },
  {
    id: 'coelophysis-ghost-ranch',
    number: '04',
    title: 'The Ghost Ranch Quarry',
    subtitle: 'New Mexico, USA - 1947',
    image: 'images/fossils/coelophysis_quarry_block.png',
    alt: 'Coelophysis quarry block fossil',
    caption: 'A dense block of Coelophysis fossils from the Ghost Ranch bonebed.',
    contain: false,
    before: 'By the mid-20th century, dinosaurs were understood as large, solitary, slow-moving creatures. The Triassic origins of the group were poorly known. Evidence for gregarious or social behaviour was essentially absent.',
    showed: 'Edwin Colbert\'s 1947 excavation at Ghost Ranch, New Mexico, unearthed hundreds - possibly thousands - of Coelophysis bauri skeletons, ranging from juveniles to adults, all buried together in a single catastrophic event. It was the largest mass accumulation of dinosaur remains ever found at the time.',
    how: 'The sheer number of individuals suggested Coelophysis lived in groups or at least aggregated seasonally. The find also demonstrated the value of catastrophic preservation: a sudden flood or drought had killed and rapidly buried a population, preserving it together. Some specimens appeared to contain small Coelophysis bones in the gut region, suggesting possible cannibalism (though this interpretation has since been questioned).',
    nuance: 'Later re-examination cast doubt on the cannibalism interpretation - the small bones inside some adults may belong to small crocodilians, not juvenile Coelophysis. The site remains the definitive reference quarry for the species and for early dinosaur population studies.',
    species: ['coelophysis'],
    people: [],
    researchCases: [],
    lastDay: false
  },
  {
    id: 'deinonychus-discovery',
    number: '05',
    title: 'Deinonychus and the Dinosaur Renaissance',
    subtitle: 'Montana, USA - 1964',
    image: 'images/fossils/deinonychus_skeleton.JPG',
    alt: 'Deinonychus skeleton',
    caption: 'Deinonychus helped overturn the image of dinosaurs as slow, sluggish animals.',
    contain: false,
    before: 'In the early 1960s, the scientific consensus held that dinosaurs were sluggish, cold-blooded reptiles - evolutionary dead ends, more like oversized lizards than dynamic animals. This view had dominated for nearly a century.',
    showed: 'John Ostrom\'s excavation and 1969 description of Deinonychus antirrhopus demolished that consensus. Deinonychus was a medium-sized predator with a rigid tail for balance, a raptorial sickle claw held off the ground, and skeletal proportions suggesting an agile, fast-moving, active predator. Its bone structure showed striking similarities to birds.',
    how: 'Ostrom\'s analysis demonstrated that Deinonychus could not have been a slow, sprawling reptile - its anatomy demanded an upright, bipedal gait and active predation style. His student Robert Bakker extended the argument: dinosaurs were likely warm-blooded, birdlike in physiology, and potentially the ancestors of modern birds. This triggered the "Dinosaur Renaissance" - a wholesale revision of dinosaur biology.',
    nuance: 'The popular image of Velociraptor as a large, intelligent pack hunter owes more to Deinonychus than to the real Velociraptor (which was turkey-sized). Jurassic Park\'s "raptors" were anatomically closer to Deinonychus. Both were later confirmed to have had feathers.',
    species: ['deinonychus', 'velociraptor', 'archaeopteryx'],
    people: ['john-ostrom', 'robert-bakker'],
    researchCases: ['theropod-hunting', 'feathers', 'family-tree'],
    lastDay: false
  },
  {
    id: 'maiasaura-nesting',
    number: '06',
    title: 'Good Mother Lizard - Dinosaur Parenting',
    subtitle: 'Montana, USA - 1978',
    image: 'images/fossils/maiasaura_nest.jpg',
    alt: 'Maiasaura nest fossil display',
    caption: 'Maiasaura nesting evidence changed how scientists thought about dinosaur reproduction and growth.',
    contain: false,
    before: 'The prevailing assumption was that dinosaurs, like most modern reptiles, laid eggs and abandoned them. Parental care was considered a mammalian and avian trait, not a reptilian one.',
    showed: 'Jack Horner and Bob Makela\'s discovery at Egg Mountain, Montana, revealed nesting colonies of Maiasaura with eggs, hatchlings, and juveniles in the same nests. Crucially, the hatchlings\' leg bones were not yet fully ossified - they could not have walked far - yet the nests contained worn-down plant material consistent with parental food delivery.',
    how: 'The nest structure, the developmental state of the hatchlings, and the presence of multiple growth stages in the same location collectively implied that Maiasaura adults returned to nests and fed their young, just as birds do. The find also revealed nesting colonies - hundreds of nests in close proximity - suggesting Maiasaura bred socially.',
    nuance: 'Not all dinosaurs are inferred to have shown parental care to the same degree. Evidence is stronger for hadrosaurs and some theropods than for sauropods or large ornithischians. The variation mirrors the range seen across modern birds and reptiles.',
    species: ['maiasaura'],
    people: [],
    researchCases: [],
    lastDay: false
  },
  {
    id: 'fighting-dinosaurs',
    number: '07',
    title: 'The Fighting Dinosaurs',
    subtitle: 'Djadochta Formation, Mongolia - 1971',
    image: 'images/fossils/fighting_dinosaurs.jpg',
    alt: 'Velociraptor and Protoceratops fighting dinosaurs fossil',
    caption: 'The Fighting Dinosaurs preserve an extraordinary predator-prey interaction.',
    contain: true,
    before: 'Fossil specimens were almost always found disarticulated, scattered by scavengers or water transport. The idea of preserving a moment of behaviour in stone was considered virtually impossible.',
    showed: 'A Polish-Mongolian expedition discovered two dinosaurs - a Velociraptor mongoliensis and a Protoceratops andrewsi - locked together and apparently preserved mid-combat. The Velociraptor\'s sickle claw was embedded in the throat region of the Protoceratops, while the Protoceratops had the Velociraptor\'s right arm in its jaws.',
    how: 'The articulation and pose are best explained by rapid burial - probably a collapsing sand dune - while both animals were still alive and struggling. The specimen provides direct evidence that Velociraptor actively preyed on (or at least fought) Protoceratops, and that the sickle claw was used in predation or combat, not merely display.',
    nuance: 'Some researchers have suggested the Velociraptor may have been scavenging rather than actively hunting, or that both animals may have died in a different position and been moved. The overwhelming consensus still favours the fighting-dinosaurs interpretation, but no fossil preserves intent.',
    species: ['velociraptor', 'protoceratops'],
    people: [],
    researchCases: [],
    lastDay: false
  },
  {
    id: 'sue-trex',
    number: '08',
    title: 'Sue - The Most Complete T. rex',
    subtitle: 'South Dakota, USA - 1990',
    image: 'images/fossils/sue_t_rex.jpg',
    alt: 'SUE the Tyrannosaurus rex skeleton',
    caption: 'SUE turned Tyrannosaurus rex from icon into a heavily studied individual life history.',
    contain: false,
    before: 'By 1990, Tyrannosaurus rex was well known but understood through fragmentary specimens. Questions about its biology - growth rate, lifespan, predatory vs. scavenging habits, sensory capabilities, soft tissue - remained largely unanswerable.',
    showed: 'Sue Hendrickson\'s discovery of FMNH PR 2081 ("Sue") produced the most complete T. rex skeleton known: approximately 90% complete and including rare elements like a wishbone, gastralia, and a nearly complete skull. Post-preparation study of the bones transformed understanding of T. rex biology.',
    how: 'Growth-ring analysis of Sue\'s bones revealed she was approximately 28 years old at death - the oldest T. rex then known - and had grown at a rate comparable to large modern mammals, not ectothermic reptiles. Sue\'s skull showed evidence of a Trichomonas-like parasite infection in the jaw (the same pathogen that affects modern raptors), and healed injuries consistent with intraspecific combat. Brain endocasts revealed large olfactory bulbs - T. rex had an exceptional sense of smell.',
    nuance: 'The legal battle over Sue\'s ownership - between fossil hunter Sue Hendrickson, landowner Maurice Williams, and the Black Hills Institute - dragged through the courts for years and led to significant changes in US fossil collection law. Sue sold at auction for $8.36 million in 1997.',
    species: ['tyrannosaurus'],
    people: [],
    researchCases: ['theropod-hunting', 'nanotyrannus', 'soft-tissue'],
    lastDay: false
  },
  {
    id: 'sinosauropteryx-liaoning',
    number: '09',
    title: 'The Feathered Dinosaurs of Liaoning',
    subtitle: 'Yixian Formation, China - 1996 onwards',
    image: 'images/fossils/sinosauropteryx_fossil.jpg',
    alt: 'Sinosauropteryx fossil with feather-like filaments',
    caption: 'Sinosauropteryx helped make feathered non-avian dinosaurs undeniable.',
    contain: true,
    before: 'Even after the Dinosaur Renaissance, feathers were still considered unique to birds. The dinosaur-bird link was theoretically strong but lacked the direct physical evidence of feathers on non-avian dinosaurs.',
    showed: 'The Yixian Formation of Liaoning Province, China, began yielding feathered non-avian dinosaurs in the 1990s. Sinosauropteryx prima (1996) was the first non-avian dinosaur found with unambiguous filamentous structures - proto-feathers. Subsequent finds - Microraptor, Anchiornis, Yi qi, and dozens more - showed that feathers or feather-like integument were widespread across the coelurosaur family tree.',
    how: 'The Liaoning specimens preserved soft tissue in extraordinary detail due to rapid burial in volcanic ash and fine lake sediments. Melanosomes - pigment-bearing organelles - were preserved in some specimens, allowing colour reconstruction. Sinosauropteryx had a ginger-and-white ringed tail. Anchiornis had black-and-white patterning with a red crest. These were not just feathered - they were colourful.',
    nuance: 'The Liaoning beds also contain some genuine avians (including Confuciusornis and early ornithurines), making the transition from feathered non-avian dinosaurs to true birds visible in a single geological formation. The interpretation of some specimens - especially Microraptor\'s four-winged gliding - remains debated.',
    species: ['sinosauropteryx', 'microraptor', 'anchiornis', 'archaeopteryx', 'velociraptor', 'yiqi', 'yutyrannus', 'wulong', 'psittacosaurus'],
    people: ['xu-xing'],
    researchCases: ['feathers', 'dinosaur-colours', 'soft-tissue'],
    lastDay: false
  },
  {
    id: 'kpg-boundary',
    number: '10',
    title: 'The K-Pg Boundary - Evidence of Impact',
    subtitle: 'Global - 1980',
    image: 'images/fossils/K_T_boundary_clay.jpg',
    alt: 'K-Pg boundary clay layer',
    caption: 'The boundary clay layer helped connect dinosaur extinction to a planetary impact event.',
    contain: false,
    before: 'The end-Cretaceous extinction had been known since the 19th century, but its cause was fiercely debated: sea-level change, volcanism, gradual climate cooling, disease. No single mechanism had global support.',
    showed: 'Luis and Walter Alvarez\'s 1980 paper reported a global layer of iridium-rich clay at the Cretaceous-Palaeogene (K-Pg) boundary - the precise horizon where non-avian dinosaurs, marine reptiles, pterosaurs, ammonites, and many other groups disappear from the fossil record. Iridium is rare in Earth\'s crust but common in asteroids. The layer was the same age worldwide.',
    how: 'The iridium anomaly, combined with shocked quartz, glass spherules, and a global soot layer, pointed to a single catastrophic asteroid impact. The identification of the Chicxulub crater beneath the Yucatán Peninsula (confirmed early 1990s) matched the predicted size and timing. The impact would have caused global wildfires, a "nuclear winter" effect, and acid rain - enough to collapse food chains worldwide.',
    nuance: 'The Deccan Traps volcanism in India was also intensifying at the end of the Cretaceous, and some researchers argue it contributed to the extinction independently or in combination with the impact. The debate over whether dinosaurs were already in decline before the impact (pre-asteroid decline) remains active.',
    species: ['tyrannosaurus', 'triceratops', 'edmontosaurus', 'ankylosaurus', 'mosasaurus', 'pteranodon', 'hesperornis', 'hatzegopteryx'],
    people: ['luis-walter-alvarez'],
    researchCases: ['pre-asteroid-decline'],
    lastDay: true
  },
  {
    id: 'spinosaurus-lost-fossils',
    number: '11',
    title: 'Spinosaurus - Lost, Found, and Rewritten',
    subtitle: 'Egypt & Morocco - 1912 / 2014',
    image: 'images/fossils/spinosaurus_skeleton.jpg',
    alt: 'Spinosaurus skeleton or reconstruction',
    caption: 'Spinosaurus is a fossil story of loss, reconstruction and ongoing debate.',
    contain: true,
    before: 'Spinosaurus aegyptiacus was described by Ernst Stromer from Egyptian material in 1915, then the original specimens were destroyed in the Allied bombing of Munich in 1944. For decades, the largest theropod known was reconstructed largely from inference and comparison with other spinosaurids. It was assumed to be a bipedal, terrestrial predator like other large theropods.',
    showed: 'Nizar Ibrahim\'s 2014 paper describing new material from Morocco - including hindlimbs, pelvic elements, and a partial skull - led to a radical reconstruction: Spinosaurus was semi-aquatic, with dense bones (for ballast), short hindlimbs relative to forelimbs, paddle-like feet, and nostrils positioned high on the skull for semi-submerged breathing. It was proposed as the first known semi-aquatic dinosaur.',
    how: 'The bone density (measured via CT scanning) was similar to penguins and other diving birds, suggesting a lifestyle spent largely in water. The proportions implied it was a poor biped on land but well-adapted for swimming or wading. Its diet - indicated by isotope analysis and gut content in related spinosaurids - was predominantly fish.',
    nuance: 'The 2014 reconstruction was immediately controversial. Critics argued the partial skeleton was from multiple individuals and that the reconstruction was too speculative. A 2020 study of tail vertebrae added strong evidence for a propulsive, crocodile-like swimming tail, broadly supporting the semi-aquatic model, though the extent to which it was truly aquatic vs. wading is still debated.',
    species: ['spinosaurus', 'baryonyx', 'giganotosaurus', 'deinosuchus'],
    people: [],
    researchCases: ['spinosaurus'],
    lastDay: false
  }
];
